export const collections = [
  "Collectie Stadsarchief Amsterdam: foto's (60.222)",
  "Collectie Stadsarchief Amsterdam: foto's eigen fotodienst (58.920)",
  "Collectie Bureau Monumentenzorg: negatiefvellen (44.555)",
  "Collectie Atelier J. Merkelbach (36.264)",
  "Archief van de Dienst Ruimtelijke Ordening: foto's afdeling B (19.938)",
  "Archief van de Dienst Ruimtelijke Ordening en rechtsvoorganger: foto's (19.237)",
  "Collectie Stadsarchief Amsterdam: tekeningen en prenten (15.952)",
  "Archief van de Dienst Bouw- en Woningtoezicht: bouwtekeningen (14.426)",
  "Archief van het Dagblad Het Vrije Volk en rechtsvoorganger: foto's (9.717)",
  "Collectie Atlas Dreesmann (7.930)",
  "Archief van de Gemeentelijke Dienst Volkshuisvesting: foto's F-serie (7.413)",
  "Collectie Stadsarchief Amsterdam: documentaire foto-opdrachten (7.016)",
  "Archief van de Gemeentelijke Dienst Volkshuisvesting en rechtsvoorganger: glasnegatieven (6.147)",
  "Archief van de Dienst Ruimtelijke Ordening: foto's afdeling A (5.874)",
  "Collectie Stadsarchief Amsterdam: bouwtekeningen (5.451)",
  "Collectie Jacob Olie Jbz. (5.381)",
  "Archief van het Bureau Monumentenzorg: glasnegatieven en negatiefloze foto's (5.345)",
  "Collectie Stadsarchief Amsterdam: prentbriefkaarten (5.339)",
  "Collectie Zuidas: foto's (5.284)",
  "Archief van Architectenbureau Baanders (5.074)",
  "Collectie Stichting IJbeeld: foto's (4.778)",
  "Archief van Cor Jaring (4.398)",
  "Archief van de Rooimeesters, later Bouwopzichters (4.082)",
  "Collectie Bernard F. Eilers (3.818)",
  "Collectie Dienst Infrastructuur Verkeer en Vervoer: foto's (3.706)",
] as const;
